bad_paths = [
    "/admin/",
    "/dbadmin/",
    "/myadmin/",
    "/mysql/",
    "/mysqladmin/",
    "/mysql-admin/",
    "/mysqlmanager/",
    "/sqlmanager/",
    "/sqlweb/",
    "/webadmin/",
    "/webdb/",
    "/websql/",

    "/p/m/a/",
    "/pma/",
    "/pma2005/",
    "/phpmyadmin/",
    "/phpmyadmin2/",
    "/php-my-admin/",
    "/php-myadmin/",
    "/phpmy-admin/",

    "/hnap1/",

    "/hudson/script",
    "/script",

    "/https:/alexwlchan.net/",

    "/.git/HEAD",

    "/themes/default/js/showdown.js",

    "/filezilla.xml",
    "/sitemanager.xml",
    "/winscp.ini",
    "/ws_ftp.ini",

    "/simpla/",
    "/umbraco",

    "/admin/content/sitetree/",

    "/cms/",
    "/netcat/",

    "/manager",
    "/manager/",

    "/core/themes/bartik/color/preview.html",

    "/id_dsa",
    "/id_rsa",
    "/.ssh/id_rsa",
    "/.ssh/id_dsa",
    "/.ssh/id_ecdsa",
    "/.ssh/id_ed25519",

    "/console",

    # These paths don"t resolve, nor is there any sensible reason to
    # expect they might resolving soon.
    "/2/favicon.ico",
    "/3/favicon.ico",
    "/home/favicon.ico",
    "/.ftpconfig",
    "/.remote-sync.json",
    "/.vscode/ftp-sync.json",
    "/deployment-config.json",
    "/sftp-config.json",

    "/console/css/dashboard-min.css",
    "/bea_wls_deployment_internal",

    "/sso/login",
]

bad_path_prefixes = [
    '/phpmyadmin-',

    '/wp-admin',
    '/wp-content',
    '/wp-includes',
    "/wp-json",
    "/wp-login",

    '/.git',

    "/.idea/",
    "/.vscode/",

    "/_backup.",
    "/db/",
    "/db_backup",
    "/sql/",

    "/index.php",
    "/user.php",
    "/xmlrpc.php",

    "/plus/ad_js.php",
    "/plus/download.php",
    "/plus/mytag_js.php",

    "/FCK/editor/",
    "/fckeditor/",
    "/admin/FCKeditor/",
    "/administrator/fckeditor/",
]

bad_path_suffixes = [
    '/uploadify/uploadify.css',
    '/fix-ie.css',

    '/phpmyadmin/',
    '/phpmyadmin',

    '/cookies.js',

    '/joomla.xml',

    '/backgroundStripe-new.jpg',
    '/footerBackground.jpg',
    '/spacer.png',

    '/ArticleBookmark@2x.png',

    '/null',

    '.ini',

    '/&',
    '/m&',

    "%20%20%20t",
    "%20%20%20et",
    "%20%20%20net",

    # File formats I don't have anywhere on the site, because I don't
    # use these technologies!
    ".asp",
    ".aspx",
    ".php",
    ".php~",
    ".php.bak",
    ".php.old",
    ".sql",
    ".sql.gz",
    ".sql.tgz",
    ".sql.zip",

    "/indy.css",

    "/alexwlchan.net.rar",
    "/alexwlchan.net.tar.gz",
    "/alexwlchan.net.tgz",
    "/alexwlchan.net.zip",

    "/wlwmanifest.xml",

    "/.env",
]

# Anything on this list was polluting 404 reports with URLs that
# wouldn't be expected to work -- but it's not a human, so I don't
# care that it got an error.
bad_user_agents = [
    'http://ahrefs.com/robot/',
    'http://megaindex.com/crawler',
    'http://mj12bot.com/',
    'http://napoveda.seznam.cz/en/seznambot-intro/',
    'http://www.baidu.com/search/spider.html',
    'http://www.similartech.com/smtbot',
    'DatabaseDriverMysqli',
    'Googlebot',
    'Newsify Feed Fetcher',
    'OpenLinkProfiler.org/bot',
    'python-requests',

    "Feedbin",
    "Feedly",
    "Feed Wrangler",
    "inoreader.com",
    "NewsBlur",
    "Overcast/1.0 Podcast Sync",
    "NetNewsWire/4.1.0",
    "theoldreader.com",

    "Bot",
    "bot",
    "Daum/4.1",
    "Qwantify/2",
    "Reeder/3",
    "YahooWebServiceClient",
]

bad_referrers = [
    'http://test-iphone-x.com/',
    'https://yellowstonevisitortours.com',
    'https://www.cloudsendchef.com',
    'https://www.timer4web.com/',
    'https://www.theautoprofit.ml',
    "http://holistickenko.com/",
    "http://www.michalstevens.top/",
    "https://www.essaybot.com/",
]

bad_referrer_components = [
    'blog1989.com',
    'incomekey.net',
    'yandex.ru',
    '/www.blog100.org/',
    "/www.hiblog.top/"
]
