language: sh

sudo: required

services:
  - docker

branches:
  only:
    - master

install:
  - echo "true"
  # - make .docker/build

script:
  - echo "false"
  # - .travis/run.sh

env:
  global:
    - RSYNC_HOST=139.162.244.147
    - RSYNC_USER=alexwlchan
    - RSYNC_DIR=/home/alexwlchan/sites/alexwlchan.net

notifications:
  email:
    - travis_alexwlchan_net@alexwlchan.fastmail.co.uk
  on_success: always
  on_failure: always
