language: sh

sudo: required

python: 3.6

services:
  - docker

branches:
  only:
    - master

cache:
  directories:
    - tests/.tox
    - ~/docker

before_script:
  - .travis/before_script.sh

script:
  - make publish
  # - .travis/run.sh

before_cache:
  - .travis/before_cache.sh

env:
  global:
    - RSYNC_HOST=139.162.244.147
    - RSYNC_USER=alexwlchan
    - RSYNC_DIR=/home/alexwlchan/sites/alexwlchan.net
