# == Hover name servers ==
#
# All my DNS records are currently hosted at Hover, and the NS records
# ensure that everyone asks Hover for my DNS records.

"alexwlchan.net NS"              = [ "ns1.hover.com.", "ns2.hover.com." ]
"alexwlchan.com NS"              = [ "ns1.hover.com.", "ns2.hover.com." ]
"alexwlchan.co.uk NS"            = [ "ns1.hover.com.", "ns2.hover.com." ]
"finduntaggedtumblrposts.com NS" = [ "ns1.hover.com.", "ns2.hover.com." ]
"bijouopera.co.uk NS"            = [ "ns1.hover.com.", "ns2.hover.com." ]



# == Fastmail DNS records ==
#
# These are the DNS records I need to use Fastmail with my domains, as
# described in Fastmail's documentation here, including:
#
#   - MX records for the Fastmail servers
#   - DKIM records in CNAME
#   - DMARC records in TXT
#   - SPF records in TXT
#
# See https://www.fastmail.help/hc/en-us/articles/1500000280261-Setting-up-your-domain-MX-only#domain-registration

"alexwlchan.net MX"                   = [ "10 in1-smtp.messagingengine.com.",
                                          "20 in2-smtp.messagingengine.com." ]
"fm1._domainkey.alexwlchan.net CNAME" = [ "fm1.alexwlchan.net.dkim.fmhosted.com." ]
"fm2._domainkey.alexwlchan.net CNAME" = [ "fm2.alexwlchan.net.dkim.fmhosted.com." ]
"fm3._domainkey.alexwlchan.net CNAME" = [ "fm3.alexwlchan.net.dkim.fmhosted.com." ]
"_dmarc.alexwlchan.net TXT"           = [ "\"v=DMARC1; p=none;\"" ]

"bijouopera.co.uk MX"                   = [ "10 in1-smtp.messagingengine.com.",
                                            "20 in2-smtp.messagingengine.com."]
"fm1._domainkey.bijouopera.co.uk CNAME" = [ "fm1.bijouopera.co.uk.dkim.fmhosted.com." ]
"fm2._domainkey.bijouopera.co.uk CNAME" = [ "fm2.bijouopera.co.uk.dkim.fmhosted.com." ]
"fm3._domainkey.bijouopera.co.uk CNAME" = [ "fm3.bijouopera.co.uk.dkim.fmhosted.com." ]
"bijouopera.co.uk TXT"                  = [ "\"v=spf1 include:spf.messagingengine.com ?all\"" ]

"finduntaggedtumblrposts.com MX"                   = [ "10 in1-smtp.messagingengine.com.",
                                                       "20 in2-smtp.messagingengine.com." ]
"fm1._domainkey.finduntaggedtumblrposts.com CNAME" = [ "fm1.finduntaggedtumblrposts.com.dkim.fmhosted.com." ]
"fm2._domainkey.finduntaggedtumblrposts.com CNAME" = [ "fm2.finduntaggedtumblrposts.com.dkim.fmhosted.com." ]
"fm3._domainkey.finduntaggedtumblrposts.com CNAME" = [ "fm3.finduntaggedtumblrposts.com.dkim.fmhosted.com." ]
"finduntaggedtumblrposts.com TXT"                  = [ "\"v=spf1 include:spf.messagingengine.com ?all\"" ]



# == Linode DNS records ==
#
# These are DNS records that point my domains at my Linode VPS, where
# I can serve them with Caddy.

"alexwlchan.net A"              = [ "178.79.134.59" ]
                                
"alexwlchan.com A"              = [ "178.79.134.59" ]
"*.alexwlchan.com A"            = [ "178.79.134.59" ]
                                
"alexwlchan.co.uk A"            = [ "178.79.134.59" ]
"*.alexwlchan.co.uk A"          = [ "178.79.134.59" ]
                                
"books.alexwlchan.net A"        = [ "178.79.134.59" ]
"www.alexwlchan.net A"          = [ "178.79.134.59" ]
"til.alexwlchan.net A"          = [ "178.79.134.59" ]
"analytics.alexwlchan.net A"    = [ "178.79.134.59" ]

"finduntaggedtumblrposts.com A" = [ "178.79.134.59" ]



# == Hover email DNS records ==
#
# I'm not sure what these are, and have no memory of setting them up --
# are these defaults for Hover or something?  I don't use email on these
# domains so it's not a big deal.

"alexwlchan.com MX"           = [ "10 mx.hover.com.cust.hostedemail.com." ]
"mail.alexwlchan.com CNAME"   = [ "mail.hover.com.cust.hostedemail.com." ]
"alexwlchan.co.uk MX"         = [ "10 mx.hover.com.cust.hostedemail.com." ]
"mail.alexwlchan.co.uk CNAME" = [ "mail.hover.com.cust.hostedemail.com." ]



# == Let's Encrypt DNS records ==
#
# This record is used to verify I own the analytics.alexwlchan.net domain
# when I create certificates with Let's Encrypt.

"_acme-challenge.analytics.alexwlchan.net TXT" = [
  # Added when renewing the certificate on 31 August 2024
  "\"BCRme-5n56EHhIpLTvNt2fb97kMJx_9nPqc9mKXnJMM\""
]



# == Masto.host DNS record ==
#
# This record allows me to use `social.alexwlchan.net` as the URL of my
# Mastodon server hosted by Masto.host.

"social.alexwlchan.net CNAME" = [ "vip.masto.host." ]



# == Bluesky DNS record ==
#
# This record allows me to use `alexwlchan.net` as my handle on Bluesky.

"_atproto.alexwlchan.net TXT" = [ "\"did=did:plc:tovvvx4o53qazoourf5u7yig\"" ]



# == TXT verification records ==
#
# These are used to prove that I own the site.  As I add more of these or
# update them, I should add comments reminding me what they're for.

"alexwlchan.net TXT" = [
  "\"ahrefs-site-verification_c8470a858a715b78845c1b81e2dc2f7aa8b367ced4cd8d342a3986a33a03b84c\"",
  "\"google-site-verification=o3zoiEGC6aLEgPMKiyWHZcRZrutF6wHQjKqhkRvgWiQ\"",
  
  # This is an SPF record for Fastmail.
  # See https://www.fastmail.help/hc/en-us/articles/1500000280261-Setting-up-your-domain-MX-only#domain-registration
  "\"v=spf1 include:spf.messagingengine.com ?all\""
]
